export interface ToolCard {
  id: string;
  name: string;
  subtitle: string;
  color: string;
  icon: string;
  textIcon: string;
  website: string;
  category: "auto" | "guide" | "manual";
  configFile?: string;
  apiEndpoint?: string;
  description: string;
  installCmd?: string;
  statusKey?: string;
  guideSteps?: Array<{ step: number; title: string; desc: string }>;
}

// Standard CLI & Terminal Tools (Direct config files / env variables)
export const CLI_TOOLS: ToolCard[] = [
  {
    id: "claude",
    name: "Claude Code",
    subtitle: "Anthropic Terminal CLI",
    color: "linear-gradient(135deg, #d97706, #b45309)",
    icon: "/providers/claude.png",
    textIcon: "CC",
    website: "https://claude.ai/download",
    category: "auto",
    configFile: "~/.claude/settings.json",
    description: "Configures ~/.claude/settings.json so all Claude Code agent commands route through your portal without shell exports.",
    installCmd: "npm install -g @anthropic-ai/claude-code",
    statusKey: "claude",
  },
  {
    id: "opencode",
    name: "OpenCode",
    subtitle: "AI Terminal Coding Agent",
    color: "linear-gradient(135deg, #ea580c, #c2410c)",
    icon: "/providers/opencode.png",
    textIcon: "OC",
    website: "https://opencode.ai",
    category: "auto",
    configFile: "~/.config/opencode/opencode.json",
    description: "Configures ~/.config/opencode/opencode.json with multiple models, primary model, and explorer subagent.",
    installCmd: "npm install -g opencode-ai",
    statusKey: "opencode",
  },
  {
    id: "codex",
    name: "Codex CLI",
    subtitle: "OpenAI Codex Agent",
    color: "#10a37f",
    icon: "/providers/codex.png",
    textIcon: "CX",
    website: "https://chatgpt.com/codex",
    category: "auto",
    configFile: "~/.codex/config.toml",
    description: "Configures ~/.codex/config.toml to set your portal as the OpenAI Responses API provider with primary & subagent models.",
    installCmd: "npm install -g @openai/codex",
    statusKey: "codex",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    subtitle: "Codeium AI IDE",
    color: "linear-gradient(135deg, #14B8A6, #0d9488)",
    icon: "/providers/windsurf.png",
    textIcon: "WS",
    website: "https://windsurf.com",
    category: "guide",
    configFile: "Windsurf Settings → Models",
    apiEndpoint: "/v1",
    description: "Use your portal as OpenAI-compatible base URL in Windsurf IDE settings. Supports all combos & models.",
    guideSteps: [
      { step: 1, title: "Open Settings", desc: "Open Windsurf Settings panel (Ctrl+, / Cmd+,)" },
      { step: 2, title: "Navigate to Models", desc: "Select 'Models' → Enable 'OpenAI Compatible API'" },
      { step: 3, title: "Paste Endpoint & Key", desc: "Paste your portal Base URL and API Key" },
      { step: 4, title: "Select Model/Combo", desc: "Set the chosen Model or Combo ID" },
    ],
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI",
    subtitle: "Google Gemini Terminal",
    color: "linear-gradient(135deg, #4285F4, #1565C0)",
    icon: "/providers/gemini-cli.png",
    textIcon: "GC",
    website: "https://github.com/google-gemini/gemini-cli",
    category: "guide",
    configFile: "OPENAI_BASE_URL env var",
    description: "Route Gemini CLI commands through your portal with automatic failover and token routing.",
    installCmd: "npm install -g @google/gemini-cli",
    guideSteps: [
      { step: 1, title: "Install CLI", desc: "Install via npm install -g @google/gemini-cli" },
      { step: 2, title: "Set Environment", desc: "Export OPENAI_BASE_URL and OPENAI_API_KEY in your terminal" },
      { step: 3, title: "Run Command", desc: "Execute gemini with your preferred model or combo" },
    ],
  },
  {
    id: "grok-cli",
    name: "Grok CLI",
    subtitle: "xAI Grok Build",
    color: "linear-gradient(135deg, #1DA1F2, #0d8ecf)",
    icon: "/providers/grok-cli.png",
    textIcon: "GK",
    website: "https://x.ai",
    category: "guide",
    configFile: "XAI_API_KEY + OPENAI_BASE_URL",
    apiEndpoint: "/v1",
    description: "Route @xai-official/grok CLI through your portal. Supports OpenAI Responses format and reasoning models.",
    installCmd: "npm install -g @xai-official/grok",
    guideSteps: [
      { step: 1, title: "Install Package", desc: "npm install -g @xai-official/grok" },
      { step: 2, title: "Export Variables", desc: "Set XAI_API_KEY and OPENAI_BASE_URL" },
      { step: 3, title: "Launch Grok", desc: "Run grok with your configured model or combo" },
    ],
  },
  {
    id: "devin-cli",
    name: "Devin CLI",
    subtitle: "Cognition Devin Agent",
    color: "linear-gradient(135deg, #6366F1, #4f46e5)",
    icon: "/providers/devin-cli.png",
    textIcon: "DV",
    website: "https://devin.ai",
    category: "guide",
    configFile: "devin config CLI",
    description: "Devin CLI ACP stdio proxy. Set base_url and api_key to route reasoning tasks through your portal.",
    installCmd: "irm https://static.devin.ai/cli/setup.ps1 | iex",
    guideSteps: [
      { step: 1, title: "Install Devin CLI", desc: "Run the install script from Cognition" },
      { step: 2, title: "Configure Base URL", desc: "devin config set base_url <gateway-url>" },
      { step: 3, title: "Configure API Key", desc: "devin config set api_key <api-key>" },
    ],
  },
  {
    id: "zed",
    name: "Zed",
    subtitle: "Next-gen Code Editor",
    color: "linear-gradient(135deg, #A855F7, #7c3aed)",
    icon: "/providers/zed.png",
    textIcon: "ZD",
    website: "https://zed.dev",
    category: "guide",
    configFile: "~/.config/zed/settings.json",
    apiEndpoint: "cloud.zed.dev/completions",
    description: "In Zed settings.json, set language_models.openai.api_url to your portal for fast autocomplete and inline assistant.",
    guideSteps: [
      { step: 1, title: "Open Zed Settings", desc: "Press Ctrl+, / Cmd+, to open settings.json" },
      { step: 2, title: "Add language_models", desc: "Configure openai endpoint to your portal URL" },
      { step: 3, title: "Set Available Models", desc: "Add your favorite models and combos to available_models" },
    ],
  },
  {
    id: "opencode-go",
    name: "OpenCode Go",
    subtitle: "OpenCode Go Subscription",
    color: "linear-gradient(135deg, #E87040, #c2602a)",
    icon: "/providers/opencode-go.png",
    textIcon: "OG",
    website: "https://opencode.ai/auth",
    category: "guide",
    configFile: "~/.config/opencode/opencode.json",
    apiEndpoint: "/zen/go/v1",
    description: "Configure OpenCode Go provider settings with your portal base URL and unified token pool.",
  },
  {
    id: "trae",
    name: "Trae",
    subtitle: "ByteDance MarsCode IDE",
    color: "linear-gradient(135deg, #FF6A00, #e55a00)",
    icon: "/providers/trae.png",
    textIcon: "TR",
    website: "https://www.trae.ai",
    category: "guide",
    configFile: "Trae Settings → AI Provider",
    apiEndpoint: "/v1",
    description: "ByteDance Trae AI code editor supports custom OpenAI-compatible endpoints with live streaming.",
  },
  {
    id: "clinepass",
    name: "ClinePass",
    subtitle: "Cline Subscription API",
    color: "linear-gradient(135deg, #5B9BD5, #2e6da4)",
    icon: "/providers/clinepass.png",
    textIcon: "CP",
    website: "https://cline.bot",
    category: "guide",
    configFile: "Cline Extension → API Provider",
    apiEndpoint: "/v1",
    description: "ClinePass proxy via your portal endpoint. Route autonomous agent coding loops through custom combos.",
    installCmd: "Install Cline extension in VS Code",
  },
  {
    id: "cline",
    name: "Cline / Roo Code",
    subtitle: "VSCode Autonomous Agent",
    color: "#00d1b2",
    icon: "/providers/cline.png",
    textIcon: "CL",
    website: "https://cline.bot",
    category: "manual",
    configFile: "VSCode Extension Settings",
    description: "Select OpenAI Compatible in Cline/Roo settings and paste your gateway endpoint. Works with any model or combo.",
    installCmd: "Install Cline extension in VS Code",
  },
  {
    id: "terminal",
    name: "Terminal / Shell",
    subtitle: "Universal Environment Vars",
    color: "var(--primary)",
    icon: "",
    textIcon: ">_",
    website: "",
    category: "manual",
    description: "Export standard environment variables in PowerShell or Bash to route any AI library or CLI through your portal automatically.",
  },
];

